### ISSUE TITLE
AttributeError: module 'jwt' has no attribute 'encode'

### ISSUE THREAD

**Issue by asajuenitan** [jpadilla/pyjwt#374] opened 2018-09-20 04:48 UTC
Using 
`import jwt`

`encoded = jwt.encode({'some': 'payload'}, 'secret', algorithm='HS256')`
**Traceback (most recent call last):
    File "< stdin >", line 1, in <module>
AttribureError: module 'jwt' has no attribure 'encode'**

Same issue with using `decode`

**Comment by vimalloc** [comment] 2018-09-20 04:49
Do you have a file called jwt.py in the same directory where you are trying to run the code?

**Comment by southwolf** [comment] 2018-11-19 17:18
You might have installed another package [jwt](https://github.com/GehirnInc/python-jwt)

Did you run `pip install jwt`? @heroh9

**Comment by venkat-pixelbrook** [comment] 2019-02-28 07:05
use "pip install pyjwt"

**Comment by lfshammu** [comment] 2019-03-03 19:19
Had a similar issue. Accidentally installed jwt first. Just removing jwt and installing PyJWT did not help.
Recreating my virtual environment and installing PyJWT fixed the issue.

**Comment by godspeedcurry** [comment] 2019-05-27 06:34
uninstall all of them then "pip install pyjwt"

**Comment by martinoywa** [comment] 2019-06-02 19:06
Uninstalling "jwt" then installing "pyjwt" worked for me.

**Comment by sandbbk** [comment] 2019-06-20 05:50
I have this problem on win10, but on debian9.9 code works correctly. In my `requirements.txt` present both `jwt` and `pyjwt` and it works on linux. When i had relocated my code from linux on windows, it didn't worked before i uninstalled `jwt`. Thanks for resolving!

**Comment by huakaidaojia** [comment] 2019-10-06 08:33
@lfshammu 我与你的情况一样，安装你的方法，一块完美解决，感谢

**Comment by Reclu3e** [comment] 2019-10-18 15:40
If your python file name is jwt.py, you may have this problem.

**Comment by parin13** [comment] 2020-03-10 17:48
`pip3 install pyjwt==1.5.3`

did the magic

**Comment by Royzzz21** [comment] 2020-06-13 09:39
thanks it works

**Comment by Royzzz21** [comment] 2020-06-13 09:40
> `pip3 install pyjwt==1.5.3`
> 
> did the magic

thanks

**Comment by vungsung** [comment] 2020-06-13 19:47
> Had a similar issue. Accidentally installed jwt first. Just removing jwt and installing PyJWT did not help.
> Recreating my virtual environment and installing PyJWT fixed the issue.

For anyone installed `jwt` directly and the Python environment cannot be easily reset:
Try this:
```bash
pip uninstall jwt
rm [Python Home Directory]/Lib/site-packages/jwt
pip uninstall pyjwt
pip install pyjwt
```

The problem is at the `site-packages/jwt` folder.
After runs `pip uninstall jwt`, the folder still exists. You have to remove it manually.
And then, the `PyJWT` folder is still stuck in `site-packages`.
You have to reinstall it in order to move it to the default `jwt` folder.

**Closed** 2020-06-15 20:12 UTC

**Comment by DestyNova** [comment] 2020-07-07 15:28
I had the same problem (but with 'decode'). The fix was as @vungsung said, but you can fix PyJWT in one step with:
```
pip install --force PyJWT
```

**Comment by PropeReferio** [comment] 2020-11-18 19:56
Can someone explain how Python is able to import jwt after you install pyjwt? Thanks.

**Comment by tonsV2** [comment] 2021-02-10 08:12
I had named my script "token.py" and that caused this error

**Comment by lugodev** [comment] 2021-02-16 14:01
> `pip3 install pyjwt==1.5.3`
> 
> did the magic

This solved my issue. Thanks!

**Comment by pcty-kk** [comment] 2021-02-24 01:53
> `pip3 install pyjwt==1.5.3`
> 
> did the magic

it works!!

**Comment by 0ccupi3R** [comment] 2021-02-26 18:40
> > `pip3 install pyjwt==1.5.3`
> > did the magic
> 
> it works!!

it worked for me too, only by keeping `pip3 install pyjwt==1.5.3` package.

**Comment by BainesySP** [comment] 2021-05-16 12:51
Hi all. I'm having this issue too. I've tried all the suggestions recommended so far and none have worked. What's even more confusing is that after uninstalling pyjwt and jwt, when I search for the jwt dir to remove it using 'locate' my terminal outputs the path but when I attempt to remove it I'm told the directory doesn't exist. I've updated my system using 'apt update' but doesn't seem to make any difference either. I'm on Python 3.9.2.

**Comment by varunlohade** [comment] 2021-05-25 14:53
pip3 install pyjwt==1.5.3 
worked for me.

**Comment by Muhammadali-Akbarov** [comment] 2022-02-04 05:11
I used all methods in comments but all does not work?

```
File "/home/muhammadali/mytaxi/jwt-custom-user/myapp/models.py", line 77, in _generate_jwt_token
    token = jwt.encode({
AttributeError: module 'jwt' has no attribute 'encode'
```

**Comment by DestyNova** [comment] 2022-02-04 20:13
> I used all methods in comments but all does not work?
> 
> ```
> File "/home/muhammadali/mytaxi/jwt-custom-user/myapp/models.py", line 77, in _generate_jwt_token
>     token = jwt.encode({
> AttributeError: module 'jwt' has no attribute 'encode'
> ```

So you tried `pip install --force PyJWT` and it didn't work? You may have to uninstall whatever package is currently providing the `jwt` module.

Alternatively you can use `virtualenv` to get a fresh virtual environment, then install PyJWT there.

**Comment by Muhammadali-Akbarov** [comment] 2022-02-18 04:06
DestyNova  thanks I'll try

**Comment by svetlanama** [comment] 2022-03-24 11:14
> > `pip3 install pyjwt==1.5.3`
> > did the magic

I works, thanks.
because of incopatibility `djangorestframework-jwt 1.11.0 requires PyJWT<2.0.0,>=1.5.2, but you have pyjwt 2.3.0 which is incompatible`

**Comment by s2t2** [comment] 2022-06-28 23:17
GitHub Actions "Python Application" is throwing this error.

**Comment by sonnguyenHT** [comment] 2023-08-03 03:50
It's work with me when I remove all jwt, pyjwt packet and install only pyjwt

**Comment by DerekNoguera** [comment] 2024-10-09 16:27
> I had the same problem (but with 'decode'). The fix was as @vungsung said, but you can fix PyJWT in one step with:
> 
> ```
> pip install --force PyJWT
> ```

Thank you very much, this helped me a lot
